#!/bin/bash

# Setup Claude Code Research Agents
# This script creates specialized agents for computational biology and clinical trial research

echo "Creating Claude Code research agents directory structure..."

# Create base directory
mkdir -p .claude/agents

# Note: Agent files are maintained in this repository under .claude/agents/
# This script can recreate them if needed, or they can be used directly from the repo

# Check if we're running from the repo root (where .claude/agents already exists with files)
if [ -d ".claude/agents" ] && [ "$(ls -A .claude/agents 2>/dev/null)" ]; then
    echo "✅ Claude Code research agents already configured!"
    echo ""
    echo "Found $(ls .claude/agents/*.md 2>/dev/null | wc -l) agent files:"
    ls -1 .claude/agents/*.md 2>/dev/null | xargs -n 1 basename | sed 's/^/    - /'
else
    echo "⚠️  No agent files found. Please clone the complete repository."
    echo "   Agent files should be in .claude/agents/"
    exit 1
fi

echo ""
echo "Directory structure:"
echo ".claude/"
echo "└── agents/"
echo "    ├── compbio-hypothesis-generator.md"
echo "    ├── compbio-dataset-specialist.md"
echo "    ├── compbio-literature-specialist.md"
echo "    ├── compbio-infrastructure-specialist.md"
echo "    ├── clinical-hypothesis-generator.md"
echo "    ├── clinical-dataset-specialist.md"
echo "    ├── clinical-literature-specialist.md"
echo "    └── clinical-infrastructure-specialist.md"
echo ""
echo "=========================================="
echo "COMPUTATIONAL BIOLOGY RESEARCHERS"
echo "=========================================="
echo ""
echo "Use these agents for genomics, proteomics, and systems biology research:"
echo ""
echo "  @compbio-hypothesis-generator"
echo "    └─ Generate research questions from omics data"
echo "       Form testable molecular hypotheses"
echo "       Examples: RNA-seq analysis, variant studies, pathway hypotheses"
echo ""
echo "  @compbio-dataset-specialist"
echo "    └─ Find genomics/proteomics datasets"
echo "       Expert in: TCGA, GTEx, GEO, UniProt, UK Biobank"
echo "       Examples: Find RNA-seq data, single-cell datasets, protein databases"
echo ""
echo "  @compbio-literature-specialist"
echo "    └─ Search bioinformatics literature"
echo "       Know journals: Bioinformatics, Genome Biology, Nature Methods"
echo "       Examples: Find CRISPR screen papers, scRNA-seq methods"
echo ""
echo "  @compbio-infrastructure-specialist"
echo "    └─ Setup bioinformatics tools and data access"
echo "       Tools: SRA Toolkit, NCBI, Ensembl, Galaxy"
echo "       Examples: Download FASTQ files, setup conda environments"
echo ""
echo "=========================================="
echo "CLINICAL TRIAL RESEARCHERS"
echo "=========================================="
echo ""
echo "Use these agents for clinical trial design and medical research:"
echo ""
echo "  @clinical-hypothesis-generator"
echo "    └─ Translate preclinical findings to clinical trials"
echo "       Design Phase I/II/III trials"
echo "       Examples: Design immunotherapy trial, select endpoints"
echo ""
echo "  @clinical-dataset-specialist"
echo "    └─ Find clinical trial and patient data"
echo "       Expert in: ClinicalTrials.gov, MIMIC, UK Biobank, Medicare claims"
echo "       Examples: Find historical controls, EHR datasets"
echo ""
echo "  @clinical-literature-specialist"
echo "    └─ Search clinical trials and medical literature"
echo "       Know journals: NEJM, Lancet, JAMA, JCO"
echo "       Examples: Find Phase III trials, practice guidelines"
echo ""
echo "  @clinical-infrastructure-specialist"
echo "    └─ Setup clinical research tools and data access"
echo "       Tools: ClinicalTrials.gov API, REDCap, PubMed E-utilities"
echo "       Examples: Query trial registries, setup HIPAA-compliant systems"
echo ""
echo "=========================================="
echo "USAGE EXAMPLES"
echo "=========================================="
echo ""
echo "Computational Biology Workflow:"
echo "  1. @compbio-hypothesis-generator Generate hypotheses from my RNA-seq data"
echo "  2. @compbio-literature-specialist Find papers on cancer drug resistance"
echo "  3. @compbio-dataset-specialist Find relevant TCGA datasets"
echo "  4. @compbio-infrastructure-specialist Download data and setup analysis environment"
echo ""
echo "Clinical Trial Workflow:"
echo "  1. @clinical-hypothesis-generator Design Phase II trial for novel drug"
echo "  2. @clinical-literature-specialist Review similar completed trials"
echo "  3. @clinical-dataset-specialist Find historical control data"
echo "  4. @clinical-infrastructure-specialist Setup REDCap and trial registry"
echo ""
echo "=========================================="
echo ""
echo "To use these agents with Claude Code:"
echo "1. Ensure you're in your project directory"
echo "2. Start 'claude' from this directory"
echo "3. Reference agents in conversations using @agent-name"
echo "4. Example: '@compbio-dataset-specialist Find scRNA-seq datasets for melanoma'"
echo ""
echo "Note: Agents are project-specific and only available when"
echo "      Claude Code is started from a directory containing .claude/agents/"
echo ""
echo "Happy researching! 🔬"
